<?php
/**
 * Default params values for joywp_testimonial_profile_card_slider_wrapper addon.
 *
 * @since 1.0
 */

return [
	'height'                                 => '400',
	'slider_controls_width'                  => '15',
	'slider_controls_height'                 => '15',
	'slider_controls_add_border'             => 'true',
	'slider_controls_border_radius'          => '15',
	'slider_controls_add_background'         => 'true',
	'slider_controls_background_color'       => '#FFFFFF',
	'slider_active_control_width'            => '26',
	'slider_active_control_height'           => '15',
	'slider_active_control_add_background'   => 'true',
	'slider_active_control_background_color' => '#FFFFFF',
	'is_fancy_background'                    => 'true',
	'items'                                  => rawurlencode(
		wp_json_encode(
			[
				[
					'testimonial'                         => "<p>Zen Doan is a business analyst, entrepreneur and media proprietor, and investor. She also known as the best selling book author.</p>\n<h3><span style=\"font-size: 24px;\"><strong>Zen</strong></span></h3>\n<p><span style=\"font-size: 18px;\"><strong>Author</strong></span></p>",
					'min_height'                          => '270',
					'image_width'                         => '34',
					'testimonial_image_source'            => 'external_link',
					'testimonial_image_image'             => '90',
					'testimonial_image_custom_src'        => 'https://i.pravatar.cc/600?img=5',
					'testimonial_image_img_size'          => 'thumbnail',
					'testimonial_image_external_style'    => 'vc_box_rounded',
					'testimonial_image_border_color'      => 'grey',
					'testimonial_image_external_border_color' => 'grey',
					'testimonial_add_border'              => 'false',
					'testimonial_border_color'            => '#cccccc00',
					'testimonial_border_style'            => 'solid',
					'testimonial_border_width'            => '1',
					'testimonial_border_radius'           => '0',
					'testimonial_add_background'          => 'true',
					'testimonial_background_type'         => 'color',
					'testimonial_background_from_gradient_color' => '#cccccc00',
					'testimonial_background_to_gradient_color' => '#cccccc00',
					'testimonial_background_color'        => '#B3B3B354',
					'testimonial_background_image_source' => 'media_library',
					'testimonial_background_image_size'   => 'auto',
					'testimonial_background_image_position' => 'default',
					'testimonial_background_image_repeat' => 'no-repeat',
					'testimonial_add_box_shadow'          => 'false',
					'testimonial_box_shadow_horizontal'   => '0',
					'testimonial_box_shadow_vertical'     => '0',
					'testimonial_box_shadow_blur'         => '0',
					'testimonial_box_shadow_spread'       => '0',
					'testimonial_add_backdrop_filter'     => 'true',
					'testimonial_backdrop_filter_type'    => 'blur',
					'testimonial_backdrop_filter_value'   => '9',
				],
				[
					'testimonial'                         => "<p>Charlie Green is an European entrepreneur and media consultant, and investor. He is the founder of the Hallmark Inc.</p>\n<h3><span style=\"font-size: 24px;\"><strong>Charlie</strong></span></h3>\n<p><span style=\"font-size: 18px;\"><strong>Hallmark Inc</strong></span></p>",
					'min_height'                          => '270',
					'image_width'                         => '34',
					'testimonial_image_source'            => 'external_link',
					'testimonial_image_image'             => '90',
					'testimonial_image_custom_src'        => 'https://i.pravatar.cc/600?img=11',
					'testimonial_image_img_size'          => 'thumbnail',
					'testimonial_image_external_style'    => 'vc_box_rounded',
					'testimonial_image_border_color'      => 'grey',
					'testimonial_image_external_border_color' => 'grey',
					'testimonial_add_border'              => 'false',
					'testimonial_border_color'            => '#cccccc00',
					'testimonial_border_style'            => 'solid',
					'testimonial_border_width'            => '1',
					'testimonial_border_radius'           => '0',
					'testimonial_add_background'          => 'true',
					'testimonial_background_type'         => 'color',
					'testimonial_background_from_gradient_color' => '#cccccc00',
					'testimonial_background_to_gradient_color' => '#cccccc00',
					'testimonial_background_color'        => '#B3B3B354',
					'testimonial_background_image_source' => 'media_library',
					'testimonial_background_image_size'   => 'auto',
					'testimonial_background_image_position' => 'default',
					'testimonial_background_image_repeat' => 'no-repeat',
					'testimonial_add_box_shadow'          => 'false',
					'testimonial_box_shadow_horizontal'   => '0',
					'testimonial_box_shadow_vertical'     => '0',
					'testimonial_box_shadow_blur'         => '0',
					'testimonial_box_shadow_spread'       => '0',
					'testimonial_add_backdrop_filter'     => 'true',
					'testimonial_backdrop_filter_type'    => 'blur',
					'testimonial_backdrop_filter_value'   => '9',
				],
				[
					'testimonial'                         => "<p>Sarah Dam is an American internet entrepreneur and media proprietor, and investor. She is the founder of the multi-national technology company Zara.</p>\n<h3><span style=\"font-size: 24px;\"><strong>Sarah</strong></span></h3>\n<p><span style=\"font-size: 18px;\"><strong>Zara Inc.</strong></span></p>",
					'min_height'                          => '270',
					'image_width'                         => '34',
					'testimonial_image_source'            => 'external_link',
					'testimonial_image_image'             => '90',
					'testimonial_image_custom_src'        => 'https://i.pravatar.cc/600?img=19',
					'testimonial_image_img_size'          => 'thumbnail',
					'testimonial_image_external_style'    => 'vc_box_rounded',
					'testimonial_image_border_color'      => 'grey',
					'testimonial_image_external_border_color' => 'grey',
					'testimonial_add_border'              => 'false',
					'testimonial_border_color'            => '#cccccc00',
					'testimonial_border_style'            => 'solid',
					'testimonial_border_width'            => '1',
					'testimonial_border_radius'           => '0',
					'testimonial_add_background'          => 'true',
					'testimonial_background_type'         => 'color',
					'testimonial_background_from_gradient_color' => '#cccccc00',
					'testimonial_background_to_gradient_color' => '#cccccc00',
					'testimonial_background_color'        => '#B3B3B354',
					'testimonial_background_image_source' => 'media_library',
					'testimonial_background_image_size'   => 'auto',
					'testimonial_background_image_position' => 'default',
					'testimonial_background_image_repeat' => 'no-repeat',
					'testimonial_add_box_shadow'          => 'false',
					'testimonial_box_shadow_horizontal'   => '0',
					'testimonial_box_shadow_vertical'     => '0',
					'testimonial_box_shadow_blur'         => '0',
					'testimonial_box_shadow_spread'       => '0',
					'testimonial_add_backdrop_filter'     => 'true',
					'testimonial_backdrop_filter_type'    => 'blur',
					'testimonial_backdrop_filter_value'   => '9',
				],
			]
		)
	),
];
